gestion/gestion/urls.py
from django.contrib import admin
from django.urls import include, path
from etudiant import views
from retard import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('etudiant/', include('etudiant.urls', namespace='etudiant')),
    path('retard/', include('retard.urls', namespace='retard')),
]

gestion/retard/urls.py
from django.urls import path, re_path

from . import views

app_name = 'retard'

urlpatterns = [
    path('', views.retard, name='retard'),
    re_path('^(?P<retard_id>[A-Z-0-9]+)/$', views.detail, name="detail")
]

gestion/retard/models.py
from django.db import models
from etudiant.models import Etudiant
# Create your models here.

class Retard(models.Model):
    identifiant = models.CharField(max_length = 10)
    semestre = models.CharField(max_length = 3, null = True)
    niveau	=	models.CharField(max_length = 10)
    matiere = models.CharField(max_length = 250)
    date = models.DateTimeField(auto_now_add=True)
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE, null=True)

gestion/retard/forms.py
# from django.forms import ModelForm, TextInput, Select
# from django.forms.utils import ErrorList
# from .models import Retard
#
# class RetardForm(ModelForm):
#     class Meta:
#         model = Retard
#         fields = ["niveau", "matiere", "identifiant"]
#         widget = {
#             'identifiant': Select(attrs={'class': 'border border-gray-500 rounded-lg'}),
#             'niveau': Select(attrs={'class': 'w-full border border-gray-500 rounded-lg'}),
#             'matiere': TextInput(attrs={'class': 'w-full border border-gray-500 rounded-lg'}),
#         }

gestion/retard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Count, Sum

from retard.models import Retard
from etudiant.models import Etudiant

def index(request):
    return render(request, 'index.html')


def add_retard(request):
    if request.method == 'POST':
        identifiant = request.POST.get('identifiant')
        niveau = request.POST.get('niveau')
        matiere = request.POST.get('matiere')
        semestre = request.POST.get('semestre')

        if identifiant and niveau and matiere and semestre:
            retard = Retard.objects.create(
                identifiant=identifiant,
                niveau=niveau,
                matiere=matiere,
                semestre=semestre
            )

        text = "<div class='w-full bg-green-200' role='alert'><span class='p-3 text-red-800'>Enregistrement effectué avec success.</span></div>"
        messages.success(request, text)
        return redirect('retard:retard')


def update_retard(request, id):
    if request.method == 'POST':
        identifiant = request.POST.get('identifiant')
        niveau = request.POST.get('niveau')
        matiere = request.POST.get('matiere')
        semestre = request.POST.get('semestre')

        if identifiant and niveau and matiere:
            retard = Retard.objects.filter(id=id).update(
                identifiant=identifiant,
                niveau=niveau,
                matiere=matiere,
                semestre=semestre
            )
        text = "<div class='w-full bg-green-200' role='alert'><span class='p-3 text-red-800'>Modification effectué avec success.</span></div>"
        messages.success(request, text)
        return redirect('retard:retard')


### START HOME ###
def retard(request):
    retard = Retard.objects.all()
    #retard = Retard.objects.order_by().values('identifiant').distinct().filter(identifiant='SE2017102')
    etudiant = Etudiant.objects.all().order_by('identifiant')

    context = {
        'retard': retard,
        'etudiant':etudiant
    }

    id = request.POST.get('id')
    if not id:
        add_retard(request)
    else:
        update_retard(request, id)

    return render(request, 'retard/home.html', context)
### END HOME ###


### START DETAIL ###
def detail(request, retard_id):
    #retard = Retard.objects.annotate(count=Count('matiere')).filter(identifiant=retard_id).distinct()
    #retard = Retard.objects.distinct().filter(identifiant=retard_id).annotate(count=Count('matiere'))
    matiere = Retard.objects.distinct().values('matiere', 'niveau', 'semestre').annotate(count=Count('matiere')).filter(identifiant=retard_id)
    semestre = Retard.objects.values('semestre').annotate(sem=Count('matiere')).filter(identifiant=retard_id).order_by('semestre')
    etudiant = get_object_or_404(Etudiant, identifiant=retard_id)

    context = {
        'etudiant_id': etudiant.identifiant,
        'etudiant_lname': etudiant.lname,
        'etudiant_fname': etudiant.fname,
        'matiere': matiere,
        'semestre' : semestre
    }
    return render(request, 'retard/detail.html', context)
### END DETAIL ###

gestion/retard/templates/retard/detail.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'menu.html' %}
{% endblock %}

{% block content %}

<div class="mg-r-15 mg-l-15">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <a href="{% url 'retard:retard' %}"><i class="fa fa-undo"></i> RETARD</a> / DETAIL
        <br>
        <div class="widget-tabs-int">
          <div class="breadcomb-wp">
              <div class="breadcomb-icon">
                  <i class="fa fa-user"></i>
              </div>
              <div class="breadcomb-ctn text-blue-900">
                  <h2><span class="uppercase-b">
                          {{ etudiant_lname }}
                          {{ etudiant_fname }}
                      </span></h2>
                  <h3>{{ etudiant_id }}</h3>
              </div>
          </div>
          <br>

            {% for semestres in semestre %}
                <h1>SEMESTRE {{ semestres.semestre }} : <span class="badge badge-pill badge-warning" style="font-size: 20px">{{ semestres.sem }}</span></h1>
            {% endfor %}
        </div>
    </div>
    <br>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="widget-tabs-int ">
        <div class="tab-hd nav nav-tabs">
            <h2>Nombre de retard de l'étudiant</h2>
        </div>

        <div>
            <div class>
                <table class="table table-striped tableau">
                    <thead>
                        <tr>
                            <th scope="col">NIVEAU</th>
                            <th scope="col">SEMESTRE</th>
                            <th scope="col">MATIERE</th>
                            <th scope="col">NOMBRE</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for matieres in matiere %}
                        <tr>
                            <td>{{ matieres.niveau }}</td>
                            <td>{{ matieres.semestre }}</td>
                            <td>{{ matieres.matiere }}</td>
                            <td>{{ matieres.count }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

gestion/retard/templates/retard/home.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'menu.html' %}
{% endblock %}

{% block content %}
<div class="mg-r-15 mg-l-15">
    <div class="breadcomb-area">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="breadcomb-list">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="breadcomb-wp">
                            <div class="breadcomb-icon">
                                <i class="fa fa-bell"></i>
                            </div>
                            <div class="breadcomb-ctn">
                                <h2>RETARD</h2>
                                <p>Gérer ici vos étudiants en retard</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="widget-tabs-int">
        <div class="tab-hd nav nav-tabs">
            <h2>Listes des étudiants en retard</h2>
        </div>
        <div>
            <div class>
                <table class="table table-striped tableau">
                    <thead>
                        <tr>
                            <th scope="col">IDENTIFIANT</th>
                            <th scope="col">NIVEAU</th>
                            <th scope="col">SEMESTRE</th>
                            <th scope="col">MATIERE</th>
                            <th scope="col">DATE / HEURE D'ARRIVEE</th>
                            <th scope="col" class="text-center">ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for retards in retard %}
                        <tr>
                            <th scope="row"><a href="{% url 'retard:detail' retard_id=retards.identifiant %}">{{ retards.identifiant }}</a></th>
                            <td>{{ retards.niveau }}</td>
                            <td>{{ retards.semestre }}</td>
                            <td>{{ retards.matiere }}</td>
                            <td>{{ retards.date }}</td>
                            <td class="text-center">
                                <span class="action edit-retard" data-id="{{ retards.id }}" data-identifiant="{{ retards.identifiant }}"
                                  data-niveau="{{ retards.niveau }}" data-matiere="{{ retards.matiere }}" data-semestre="{{ retards.semestre }}">
                                    <i class="fa fa-edit text-green-700 mx-2"></i>
                                </span>
                                <!-- <span class="action edit-retard">
                                    <a href="{% url 'retard:detail' retard_id=retards.identifiant %}">
                                        <i class="fa fa-eye text-blue-500 mx-2"></i>
                                    </a>
                                </span> -->
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div>
        <div class="tab-hd nav nav-tabs"></div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message|safe }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <br>

        <div class="widget-tabs-int mgt-15">
            <form id="item_form" action="{% url 'retard:retard' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input id="retard-id" type="hidden" name="id" value="" />
                <div class="flex flex-wrap form-content justify-between">
                    <div class="form-item mb-3">
                        <label for="">IDENTIFIANT </label>
                        <select id="retard-identifiant" class="w-full border border-gray-800 rounded-lg" name="identifiant">
                            <option selected="selected">Selectionnez-ici</option>
                            {% for identifiant in etudiant %}
                            <option value="{{identifiant.identifiant}}">{{identifiant.identifiant}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-item mb-3">
                        <label for="">NIVEAU</label>
                        <select id="retard-niveau" class="w-full border border-gray-800 rounded-lg" name="niveau">
                            <option selected="selected">Selectionnez-ici</option>
                            <option value="L1 IRD">L1 IRD</option>
                            <option value="L1 TC">L1 TC</option>
                            <option value="L2 BANCAS">L2 BANCAS</option>
                            <option value="L2 IRD">L2 IRD</option>
                            <option value="L2 MEGP">L2 MEGP</option>
                            <option value="L3 BANCAS">L3 BANCAS</option>
                            <option value="L3 IRD">L3 IRD</option>
                            <option value="L3 MEGP">L3 MEGP</option>
                        </select>
                    </div>

                    <div class="form-item mb-3">
                        <label for="">SEMESTRE</label>
                        <select id="retard-semestre" class="w-full border border-gray-800 rounded-lg" name="semestre">
                            <option selected="selected">Selectionnez-ici</option>
                            <option value="S1">S1</option>
                            <option value="S2">S2</option>
                            <option value="S3">S3</option>
                            <option value="S4">S4</option>
                            <option value="S5">S5</option>
                            <option value="S6">S6</option>
                        </select>
                    </div>

                    <div class="form-item mb-3">
                        <label for="">MATIERE</label>
                        <input id="retard-matiere" class="w-full border border-gray-800 rounded-lg" type="text" name="matiere" value="" required />
                    </div>

                    <div>
                        <div class="flex mb-3 justify-end">
                            <input class="btn btn-primary m-3" type="submit" value="ENREGISTRER">
                            <input class="btn btn-danger m-3 cancel" type="submit" value="ANNULER">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}